### ISSUE TITLE
auto update not working 

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/dddosdb-in-a-box#1]
Auto-update is not working for repositories with one tag.

Checking updates for https://github.com/ddos-clearing-house/ddos_dissector
Traceback (most recent call last):
  File "update_repo.py", line 70, in <module>
    if semver.compare(v, vlatest) == 1:
  File "/home/ddosdb/.local/lib/python3.7/site-packages/semver.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/ddosdb/.local/lib/python3.7/site-packages/semver.py", line 786, in compare
    v1 = VersionInfo.parse(ver1)
  File "/home/ddosdb/.local/lib/python3.7/site-packages/semver.py", line 656, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: 3.0 is not valid SemVer string

**Comment by poorting** [comment]
Problem here is not the presence of just one tag, but the tag not being in the right 'semantic versioning' format of vX.Y.Z, with X=Major version, Y=Minor verion and Z=Patch version. But the script still shouldn't crash of course!
I've added a check to the script to see whether it is a semantic version tag, before processing it further (so it should now ignore tags that do not use that convention). 
Setting a tag v3.0.0 should work however.
